name: 'GaPve'
description: 'Create Python virtual environement'
inputs:
  python-version: 
    description: 'Python version for the virtual environement'
    required: true
  requirements-file: 
    description: 'Path to requierement file'
    required: true
  run-command: 
    description: "Command to run"
    required: true 

runs:
  using: "composite"
  steps:
    - name : setup python virtual env 
      uses: actions/setup-python@v4.7.1
      with:
        python-version: ${{ inputs.python-version }}

    - name : install Dependencies and run 
      run : | 
        python -m venv venv
        source venv/bin/activate
        pip install -r ${{inputs.requirements_file}} 
        ${{ inputs.run_command}} 
      shell : bash 

