name: 'GaPve'
description: 'Create Python virtual environement'
inputs:
  python-version: 
    description: 'Python version for the virtual environement'
    required: true
  requirements-file: 
    description: 'Path to requierement file'
    required: false 
  contraints-file:
    description : "Path to constrain file"
    required: false 
  requirements:
    description: "Specific requirements"
    required : false 
  constraints: 
    description: "Specific constrains"
    required: false 
  run-command: 
    description: "Command to run"
    required: true 

runs:
  using: "composite"
  steps:
    - name : setup python virtual env 
      uses: actions/setup-python@v4.7.1
      with:
        python-version: ${{ inputs.python-version }}

    - name: 'Install Dependencies and run'
      run: | 
        python -m venv venv
        if [ -f venv/bin/activate ]; then
          source venv/bin/activate  
        else # on windows 
          .\venv\Scripts\activate
        fi

        if [ -n "${{ inputs.requirements-file }}" ]; then
          pip install -r "${{ inputs.requirements-file }}"
        fi

        if [ -n "${{ inputs.constraints-file }}" ]; then
          pip install -c "${{ inputs.constraints-file }}"
        fi

        if [ -n "${{ inputs.requirements }}" ]; then
          pip install ${{ inputs.requirements }}
        fi

        if [ -n "${{ inputs.constraints }}" ]; then
          pip install  ${{ inputs.constraints }}
        fi

        eval "${{ inputs.run-command }}"
      shell: bash
