name: 'GaPve'
description: 'Create Python virtual environement'
inputs:
  python-version: 
    description: 'Python version for the virtual environement'
    required: true
  requirements-file: 
    description: 'Path to requierement file'
    required: false 
  contraints-file:
    description : "Path to constrain file"
    required: false 
  requirements:
    description: "Specific requirements"
    required : false 
  constraints: 
    description: "Specific constrains"
    required: false 
  run-command: 
    description: "Command to run"
    required: true 

runs:
  using: "composite"
  steps:
    - name : setup python virtual env 
      uses: actions/setup-python@v4.7.1
      with:
        python-version: ${{ inputs.python-version }}

    - name: 'Create venv'
      run: | 
        python -m venv venv
        if [ -f venv/bin/activate ]; then
          source venv/bin/activate  
        else # on windows 
          .\\venv\\Scripts\\activate
        fi
      shell: bash
    

    - name: Install dependencies
      run: |
        if [ -n "${{ inputs.requirements-file }}" ] && [ -n "${{ inputs.constraints-file }}" ]; then
          pip install -r "${{ inputs.requirements-file }}" -c "${{ inputs.constraints-file }}"
        elif [ -n "${{ inputs.requirements-file }}" ]; then
          pip install -r "${{ inputs.requirements-file }}"
        fi
      shell: bash

    - name: Install manual dependencies
      run: |
        if [ -n "${{ inputs.requirements }}" ] && [ -n "${{ inputs.constraints }}" ]; then
          echo "${{ inputs.requirements }}" > requirements.txt
          echo "${{ inputs.constraints }}" > constraints.txt
          pip install -r requirements.txt -c constraints.txt
        elif [ -n "${{ inputs.requirements }}" ]; then
          echo "${{ inputs.requirements }}" > requirements.txt
          pip install -r requirements.txt
        fi
      shell: bash

    - name : "Run commands" 
      run :  eval "${{ inputs.run-command }}"
      shell : bash 

