name : test script 

on : push

jobs: 
  build: 
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.11] 

    steps:
      - name : Checkout repo 
        uses : actions/checkout@v4.1.1
      
      # - name: Print current folder
      #   run: |
      #     echo "Current folder: $(pwd)"

      - name : test script 
        uses : ./actions/GaPve
        with : 
          python-version :  ${{ matrix.python-version }}
          requirements-file : "requirements.txt"
          requirements: "django"
          constraints: "django>=4.0.0"
          run-command : "python script.py"





